### ISSUE TITLE
Not working, dead silent

### ISSUE THREAD

**Issue by BlackReaper33** [wotschofsky/discord-live-translator#56] opened 2023-10-05 03:04 UTC
So i ran all the commands as stated except ```pnpm run deploy```
Bot joins the voice chat i input the start command and choose my target language and after that bot is dead silent 
Help

**Comment by wotschofsky** [comment] 2023-10-08 20:47
Hi @BlackReaper33, can you please post (a) the logs from the bot and (b) a screenshot of the bot has on your server

**Comment by BlackReaper33** [comment] 2023-10-09 04:21
where will i find logs of the bot?

**Comment by BlackReaper33** [comment] 2023-10-16 06:20
there are no logs @wotschofsky 
![2](https://github.com/wotschofsky/discord-live-translator/assets/84635243/78ee4dc9-e246-4493-9fa7-6ecdb716157e)

**Comment by wotschofsky** [comment] 2023-10-16 06:40
If you run the `docker compose` command without `-d` (detached mode), you will see the logs from the individual containers.

**Comment by BlackReaper33** [comment] 2023-10-16 08:21
im not sure whats wrong
![2](https://github.com/wotschofsky/discord-live-translator/assets/84635243/c433ea01-0f7f-4f54-958a-7850147daf5b)

**Comment by wotschofsky** [comment] 2023-10-17 10:18
Thank you for posting this! It looks like this is a duplicate of #42, therefore I'll close this issue. Please feel free to watch the other issue.

**Closed by wotschofsky** 2023-10-17 10:18 UTC
