### ISSUE TITLE
 ERR_PNPM_CANNOT_DEPLOY 

### ISSUE THREAD

**Issue by BlackReaper33** [wotschofsky/discord-live-translator#53] opened 2023-09-23 14:24 UTC
same issue as i opened few weeks ago

user:/home/user/discord-live-translator# docker exec discord-live-translator-bot-1 pnpm run deploy
```OCI runtime exec failed: exec failed: unable to start container process: exec: "pnpm": executable file not found in $PATH: unknown```
user:/home/user/discord-live-translator# pnpm deploy
``` ERR_PNPM_CANNOT_DEPLOY  A deploy is only possible from inside a workspace```

**Comment by wotschofsky** [comment] 2023-09-24 10:07
Hi @BlackReaper33, this isn't an issue with the codebase itself.
As described in my comment on #44, I've updated the documentation. If you follow the updated README instructions, you should be good.

**Comment by BlackReaper33** [comment] 2023-09-24 18:01
can we use node 18 instead on 20?
18 is more stable and im using alpine linux so node 20 isnt avaiable yet...

**Comment by wotschofsky** [comment] 2023-09-25 08:54
Are you running the bot inside Docker or directly on your host system? I remember choosing a Debian based image due to the TTS not really working on Alpine.

Regarding the Node.js version: v20 is only one month away from LTS and it's not like v20 super unstable. I have yet to run into any issues. But please, correct me if I am wrong!

Either way I've been thinking of moving to Bun for this anyways, but I'm not sure yet.

**Comment by BlackReaper33** [comment] 2023-09-25 09:59
Running directly onto the host system 

So if i modify file to run node 18 it will not run into issues at least it shouldn't right?

I would suggest bun. New technology faster and optimised better

**Comment by wotschofsky** [comment] 2023-09-29 21:17
As far as I know, pnpm only displays a warning if the Node.js version on your system does not match the version specified in package.json.  It doesn't prevent you from running the script.

**Comment by BlackReaper33** [comment] 2023-09-30 09:23
so its not giving any output vc whatever im saying its not translating
i did not the pnpm command because it was just an alternative and did not set guild id because i ran commands manually

so please help

**Comment by wotschofsky** [comment] 2023-09-30 10:46
The original concern seems to have been resolved, which is why I am closing this issue.

If you need further assistance, please open a new issue with the steps to reproduce your setup. And also please include application logs.

**Closed by wotschofsky** 2023-09-30 10:46 UTC
